### ISSUE TITLE
[SOLVED] Are you positively absolutey sure that Ubuntu22.04(.3) is supported?

### ISSUE THREAD

**Issue by brianr-dk** [codership/galera-manager-support#77] opened 2023-12-08 09:02 UTC
I have set up a rather simple testbed - four Virtualbox Ubuntu22.0.3 servers. 

On the forth I've set up galera-manager. Thee gm-installer ran fine and  GUI is accessible. 

From GUI I've asked gm to deploy a node on the first ubuntu1 node. 
It fails in no time with "unsupported os"? 

Is there a way to ask it to be more verbose, so I can se what it asks and what it receives? 

Here's a text dump of the gm GUI output. I'd format it if only I understood "Markdown", but I don't... 

**galeracluster cluster deployment logs**
	Timestamp	Channel	Message
	2023-12-04 13:42:31	app	empty cluster created
channel-type: app
cluster-id: '1'
file: /go/pkg/internal/mgmt/clusters.go:672
func: >-
  github.com/codership/galera-manager/pkg/internal/mgmt.(*Clusters).Create.(*Clusters).createFn.func1
level: info
msg: empty cluster created
time: '2023-12-04T12:42:31Z'

	2023-12-04 14:35:25	app	creating cluster detailed		

	2023-12-04 14:35:25	app	deploying host		

	2023-12-04 14:35:25	app	host deployment error		
_context:
  jobID: '8'
channel-type: app
cluster-id: '1'
**error:
  msg: unsupported operating system**
file: /go/pkg/internal/mgmt/units/cluster.go:124
func: >-
  github.com/codership/galera-manager/pkg/internal/mgmt/units.(*Cluster).CreateDetailed.func1
host-name: 192.168.56.91
level: error
msg: host deployment error
time: '2023-12-04T13:35:25Z'

	2023-12-04 14:35:25	app	not all hosts were created		
_context:
  jobID: '8'
channel-type: app
cluster-id: '1'
file: /go/pkg/internal/mgmt/units/cluster.go:164
func: >-

**Comment by brianr-dk** [comment] 2023-12-08 09:08
Oh - the version verification. I forgot: 

Both hosts responds this to  "lsb_release -a" : 
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Comment by ketomagasaki** [comment] 2023-12-10 16:43
Hello,

Same issue when I try with version 22.04.3 LTS, as well as without updating, the 22.04:

```
# lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

**Comment by byte** [comment] 2023-12-11 15:38
root@2204:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

./gm-installer version
gm-installer version 1.11.0 (linux/amd64)

It works

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

./gm-installer install
INFO[0000] OS Detected: Debian / Ubuntu / Linux / jammy / 22.04 

It works.

So at this stage we know that the installer, installs, and works.

However, trying to deploy a cluster on a user-provided host (Galera Cluster MySQL 8, which has packages for 22.04), we do see this failure:

cat /var/log/gmd/cluster-1-host-1.log 
{"_context":{"jobID":"6"},"channel-type":"app","cluster-id":"1","error":{"msg":"unsupported operating system"},"file":"/go/pkg/internal/mgmt/clusters.go:716","func":"github.com/codership/galera-manager/pkg/internal/mgmt.(*Clusters).hostCreateFn.func1","host-id":"1","host-name":"node1","level":"error","msg":"failed to deploy host","time":"2023-12-11T15:33:10Z"}
{"channel-type":"app","cluster-id":"1","file":"/go/pkg/internal/mgmt/hosts.go:226","func":"github.com/codership/galera-manager/pkg/internal/mgmt.(*Hosts).Delete","host-id":"1","level":"warning","msg":"Hosting client initialization failed (unsupported operating system), removing only db record","time":"2023-12-11T15:34:20Z"}
{"_context":{"jobID":"8"},"channel-type":"app","cluster-id":"1","file":"/go/pkg/internal/mgmt/units/host.go:161","func":"github.com/codership/galera-manager/pkg/internal/mgmt/units.(*Host).Delete","host-id":"1","level":"info","msg":"deleting host","time":"2023-12-11T15:34:20Z"}
{"_context":{"jobID":"8"},"channel-type":"app","cluster-id":"1","file":"/go/pkg/internal/mgmt/units/host.go:364","func":"github.com/codership/galera-manager/pkg/internal/mgmt/units.(*Host).deleteFromDB","host-id":"1","level":"info","msg":"deleting host from DB","time":"2023-12-11T15:34:20Z"}

So can confirm and repeat as reported.

**Comment by brianr-dk** [comment] 2023-12-12 12:54
Thanks, Colin. 

I've doucblechekced and my installer is also 1.11.0 on the server I try installing on. 

I don't know what the "user provided host" means. I guess my host is also user provided since *I* created/provided the host as an  Ubuntu22.0.4.3 clean install. 
(Any hard requirements on Ubuntu, to allow  gm-installer  to run?) 

But the 1.11.0 gm-installer still quits with "unsupported os", when I ask it to deploy to the remote VM wich is a clone of the same Ubuntu22.0.4.3 guest that runs the gm-installer ? 
The clone or the galeramanager guest has no mariadb installed, I'd try to see what it would require to let gm-installer handle "all that jazz".  


But now I read you test as if the error is with me (and ketomagasaki) - but I don't know where my fault lies. 


Regards 
Brian

**Comment by brianr-dk** [comment] 2023-12-12 12:58
I am sorry - of course it's NOT the gm-installer that quits!  
Clarifying: It is the [running and working] Galera Manager that was installed to node 4, when it tries to deploy a node to the first of my cloned Ubuntu nodes (all 22.0.4.3 clones from the same template, with new MAC's/Addresses) 

( When asking it to deploy mariadb 10.11 to Ubuntu22.04 on node 1. )


I have tried understanding the Galera Manager Log you have in the GUI - pretty neat! 
But I am not sure if the content reveals why your GM 1.8 should refuse to install on my first Ubuntu22.04 node?

**Maybe someone can shed light on the log from the attempt to deploy a node1?  :** 
(Copied directly from GUI (html) in to text : ) 
 
2023-12-13 09:17:17	root@192.168.56.91# echo -n "test"
2023-12-13 09:17:18	test
2023-12-13 09:17:18	Creating MariaDB-client
2023-12-13 09:17:18	192.168.56.91:22$ bash -c 'echo $(apt-cache policy mariadb-client | grep Installed | awk '"'"'{$1=""; print $0}'"'"') '
2023-12-13 09:17:18	(none)
2023-12-13 09:17:18	Creating MariaDB-client-core
2023-12-13 09:17:18	192.168.56.91:22$ bash -c 'echo $(apt-cache policy mariadb-client-core | grep Installed | awk '"'"'{$1=""; print $0}'"'"') '
2023-12-13 09:17:18	
2023-12-13 09:17:18	Creating MariaDB-common
2023-12-13 09:17:18	192.168.56.91:22$ bash -c 'echo $(apt-cache policy mariadb-common | grep Installed | awk '"'"'{$1=""; print $0}'"'"') '
2023-12-13 09:17:18	(none)
2023-12-13 09:17:18	
2023-12-13 09:17:18	Creating MariaDB-server
2023-12-13 09:17:18	192.168.56.91:22$ bash -c 'echo $(apt-cache policy mariadb-server | grep Installed | awk '"'"'{$1=""; print $0}'"'"') '
2023-12-13 09:17:19	(none)
2023-12-13 09:17:19	
2023-12-13 09:17:19	Creating MariaDB-server-core
2023-12-13 09:17:19	192.168.56.91:22$ bash -c 'echo $(apt-cache policy mariadb-server-core | grep Installed | awk '"'"'{$1=""; print $0}'"'"') '
2023-12-13 09:17:19	
2023-12-13 09:17:19	Creating galera
2023-12-13 09:17:19	192.168.56.91:22$ bash -c 'echo $(apt-cache policy galera-3 | grep Installed | awk '"'"'{$1=""; print $0}'"'"') '
2023-12-13 09:17:19	(none)
2023-12-13 09:17:19

**Comment by brianr-dk** [comment] 2023-12-13 09:07
DANG!   

I was just about to write another entry here - until I read that **you actually CONFIRM** that "Deploy on User Provided Hosts" is **not** working on Ubuntu22.04 (With either Mysql or Mariadb)! 

Thanks a lot. I will sit tight and wait.

**Comment by byte** [comment] 2023-12-19 13:42
gm-installer 1.11.0 is released and it looks like it fixes this issue

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

./gm-installer version
gm-installer version 1.11.0 (linux/amd64)

I can confirm I deployed 1 node, without issue. So the other 2 nodes, should be fine.

show status like 'wsrep_cluster_size';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| wsrep_cluster_size | 1     |
+--------------------+-------+
1 row in set (0.00 sec)

**Comment by ketomagasaki** [comment] 2023-12-19 16:38
I add new third node :

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Galera Manager 1.8.1

Deploy OK

```
MariaDB [(none)]> show status like 'wsrep_cluster_size';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| wsrep_cluster_size | 3     |
+--------------------+-------+
1 row in set (0.001 sec)
```

But I'm not sure if this is perfect, I tried to connect to the new node with PhpMyAdmin, and I got an error "MySQL server has gone away." No issues with nodes 1 and 2 with PhpMyAdmin. I can connect via cmd from the PhpMyAdmin VM to the new node.

I'm searching...

Edit: Forgot my mistake, I made an error in the my.cnf to include my SSL certificate.

**Comment by byte** [comment] 2023-12-27 03:42
@brianr-dk can you confirm it works and installs as planned? I will then close the issue

**Comment by byte** [comment] 2023-12-27 03:43
> I add new third node :
> 
> lsb_release -a No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 22.04.3 LTS Release: 22.04 Codename: jammy
> 
> Galera Manager 1.8.1
> 
> Deploy OK
> 
> ```
> MariaDB [(none)]> show status like 'wsrep_cluster_size';
> +--------------------+-------+
> | Variable_name      | Value |
> +--------------------+-------+
> | wsrep_cluster_size | 3     |
> +--------------------+-------+
> 1 row in set (0.001 sec)
> ```
> 
> But I'm not sure if this is perfect, I tried to connect to the new node with PhpMyAdmin, and I got an error "MySQL server has gone away." No issues with nodes 1 and 2 with PhpMyAdmin. I can connect via cmd from the PhpMyAdmin VM to the new node.
> 
> I'm searching...
> 
> Edit: Forgot my mistake, I made an error in the my.cnf to include my SSL certificate.

Unsure if this is an error or not since you made the edit, can you please file a new issue if you're finding issues (since this is unrelated). also, why might you need phpmyadmin when Galera Manager handles everything?

**Comment by ketomagasaki** [comment] 2023-12-27 15:02
No, no, I had edited my message; I had made a typo in the SSL certificate name.

I use PHPMyAdmin to have a visual representation of each database and to easily make modifications if an application encounters an issue.

**Closed as completed** 2024-01-08 09:44 UTC
